Feature/applyment context
Pre-Onboarding-FE-Team07/wanted-codestates-project-7-6 pull request #25
Opened 2022-03-09 06:49 UTC by ye-yo

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [X] 기능 추가
- [ ] 기능 삭제
- [X] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
dev <- feature/applyment_context
### 변경 사항
#### 1. 신청 내역 Context
- 신청 내역에 데이터 표시 위해 `ApplymentBriefContext` 추가
- 이전 step으로 돌아갔을 때 작성했던 내역 표시위해 `applymentBrief` 데이터가 있을 경우 state default 값으로 적용
    -  이 과정에서 각 step 페이지 및 context 코드에 변경이 있었습니다.
    - ex) DateContext에 `setStartEndDate()` 함수가 추가됨
- 신청 내역에서 데이터 포맷을 변경하여 표시하기 위해 함수 추가 utilities/date.js의 `formatDateKorean()`
- 최종 신청서 데이터 형식은  API 명세와 동일하게 맞추기 위해 함수 추가 :  utilities/date.js - `formatDateDash(), formatTime()`

#### 2. 그외 수정 
- 다음 버튼 클릭시 `setActiveNext` false로 변경
- overflow 문제 해결위해 디자인 수정 - 현재 코드는 헤더를 고정하지 않은 버전입니다.
- `StepApplymentBrief` 코드에 연락처 인증되었을 때 다음 버튼을 활성화하는 코드를 추가하였으나 
인증없이 테스트를 위해 현재 주석처리 해두었습니다.

### 확인 사항
- #24 PR 부분도 포함되어 있습니다. PR은 close 해두었으니 본 PR에서 함께 확인해주세요.
- 24시간 상주 선택시 돌봄 스케줄의 시간 선택 disabled 처리 및 24시간으로 표시되도록 처리가 필요합니다.

### 테스트 결과
<img width="400px" src="https://user-images.githubusercontent.com/50618754/157387485-725877a3-74fe-4f92-b354-98100a10dcf7.gif"/>

2022-03-09 07:18 UTC, Lela12 approved these changes
OK: 확인했습니다. 고생하셨습니다!!

2022-03-09 07:35 UTC, Lee-ye-ji requested changes
`Recommend-Must`: 효은님 고생이 많으십니다...! 제가 Address Context 부분에 디테일주소도 넣을 수 있게 코드를 작성해두었습니다. 아래 형식을 보셔서 AddressDetail을 그 부분에 추가해주시고 마지막에 효은님이 작성해두신 applymentBrief를 이용하셔서 주소에 대한 데이터와 달력, 그리고 나머지 데이터를 합쳐서 작성해주시는 방식이 지금의 코드로는 더 좋을 것 같다는 생각이 듭니다!
```jsx
  const addressValue = {
    addressDetail: String,
    jibunAddress: String,
    liName: String || null,
    locationCode: String,
    roadCode: String,
    myundongName: String,
    roadAddress: String,
    sidoName: String,
    sigunguName: String,
  };
```

2022-03-09 07:59 UTC, ye-yo commented
> `Recommend-Must`: 효은님 고생이 많으십니다...! 제가 Address Context 부분에 디테일주소도 넣을 수 있게 코드를 작성
...

네 예지님 addressContext에 넣는 것으로 수정하겠습니다!

2022-03-10 01:15 UTC, Lee-ye-ji approved these changes
`Good`: 늦게까지 고생많으셨습니다!

2022-03-10 01:17 UTC, merged