Feat : 스케줄뷰 페이지 추가
Pre-Onboarding-FE-Team07/wanted-codestates-project-7-6 pull request #8
Opened 2022-03-07 14:08 UTC by jeonghun10

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
dev <- feat/scheduleView

### 변경 사항
스케줄 뷰 페이지 추가했습니다.

### 테스트 결과

2022-03-07 14:44 UTC, jinyongp requested changes
그냥 봐선 파악하기 힘드니, 작성한 컴포넌트 스크린샷 추가 부탁드립니다.

2022-03-07 14:44 UTC, jinyongp commented on src/constants/staticData.jsx
> +export const timeList = [
~jsx가 사용되지 않은 경우엔 jsx가 아닌 js로 생성해주세요.~

2022-03-07 14:44 UTC, jinyongp commented on src/constants/staticData.jsx
> +export const timeList = [
~1. 상수의 경우 네이밍 컨벤션에 따라 모든 문자를 대문자로 하시고 띄어쓰기는 `_`로 구분해주세요. `TIME_LIST`
2. 객체로 구성된 상수일 경우 내부 값이 변경될 여지가 있습니다. [해당 글](https://stackoverflow.com/q/39027562/9735184)을 참조하여 상수 값이 변경되지 않도록 처리해주세요.~

2022-03-07 14:44 UTC, jinyongp commented on src/constants/staticData.jsx
> +export const timeList = [
staticData의 경우 api로 불러오는 걸로 알고있는데 직접 만드신 이유가 무엇인가요? 만약 fakeData로 사용할 예정이시라면 임시 폴더를 생성해서 옮겨주세요.

2022-03-07 14:44 UTC, jinyongp commented on src/pages/Schedule.jsx
> +const Schedule = () => {
다른 파일과 마찬가지로 일관성을 가지도록 특별한 이유가 없다면 `export default function Schedule`로 작성해주세요.

2022-03-07 14:44 UTC, jinyongp commented on src/pages/Schedule.jsx
> +const ContainerStyled = styled.div`
styled 컴포넌트 사이마다 공백을 삽입하는 것이 가독성 측면에서 더 좋아보입니다.

2022-03-07 14:44 UTC, jinyongp commented on src/pages/Schedule.jsx
> +const CalendarButton = styled.div`
Button인데 div 태그로 작성하는 건 접근성 측면에서 좋아보이지 않습니다. semantic tag를 적극 이용해주세요.

2022-03-07 14:44 UTC, jinyongp commented on src/pages/Schedule.jsx
> +          <div>시작일</div>
text를 표현할 때 div 태그보단 적절한 [HTML Text Tag](https://flaviocopes.com/html-text-tags/)를 이용해주세요.

2022-03-07 14:44 UTC, jinyongp commented on src/pages/Schedule.jsx
> +          })}
화살표 함수에서 곧장 반환하는 경우 return이 필요 없습니다.
```suggestion
          {careTimeList.map((el, idx) => <option key={idx}>{el.text}</option>)}
```
이렇게 더 깔끔하게 작성할 수 있습니다.

2022-03-07 15:44 UTC, dev-seomoon requested changes
`Recommend-Must`

2022-03-07 15:44 UTC, dev-seomoon commented on src/pages/Schedule.jsx
> +      <h2>돌봄 스케줄을 설정해주세요</h2>
내부 타이틀은 페이지 컨테이너에 공통 컴포넌트로 구현되어 있으므로 제거하셔도 됩니다.

2022-03-07 15:44 UTC, dev-seomoon commented on src/pages/Schedule.jsx
> +      <SelectWrapStyled>
`<SelectWrapStyled />`는 동일한 코드가 두 번 중복되니까
별도의 컴포넌트로 분리하는 것이 좀 더 가독성이 좋을 것 같습니다.

2022-03-07 15:44 UTC, dev-seomoon commented on src/pages/Schedule.jsx
> +`;
Figma에서 스타일 속성을 확인하셔서 Figma와 일치하게 스타일링해주세요. 
스타일 차이가 큽니다.

2022-03-07 15:44 UTC, dev-seomoon commented on src/pages/Schedule.jsx
> +        <span>하루 돌봄 시간</span>
span 태그 대신 label 태그를 사용해주세요. 
https://developer.mozilla.org/ko/docs/Web/HTML/Element/select

2022-03-07 15:44 UTC, dev-seomoon commented on src/pages/Schedule.jsx
> +        <span>돌봄 시작 시간</span>
span 대신 label 태그를 사용해주시는 것이 좀 더 시맨틱합니다. 
https://developer.mozilla.org/ko/docs/Web/HTML/Element/select

2022-03-07 15:44 UTC, dev-seomoon commented on src/pages/Schedule.jsx
> +    <ContainerStyled>
Styled-component 이름이 컴포넌트와 겹치는게 아니라면, 
모든 스타일드 컴포넌트 이름 끝에 Styled를 꼭 붙여야 할 필요는 없습니다. 
Styled를 제거하는 것이 더 가독성이 좋을 것 같아요.

2022-03-07 15:44 UTC, dev-seomoon commented on src/pages/Schedule.jsx
> +            <option key={idx}>{el.text}</option>
인덱스를 키값으로 사용하지 말아주세요.

2022-03-08 05:19 UTC, dev-seomoon approved these changes

2022-03-08 05:22 UTC, merged